#!/usr/bin/env python3
"""mkgenmidi.py GENMIDI.LMP > GENMIDI.C

Converts a DMX GENMIDI (OP2) instrument bank into the C table of VSBHDA.DRV.
The bank used is Freedoom's (lumps/genmidi, built with its mkgenmidi):
BSD-3-Clause, Copyright (c) 2001-2024 Contributors to the Freedoom project."""
import sys

d = open(sys.argv[1], 'rb').read()
assert d[:8] == b'#OPL_II#' and len(d) >= 8 + 175 * 36
print('''/* GENMIDI.C: General MIDI instrument bank (DMX "OP2" format) for the FM
 * synthesizer of VSBHDA.DRV, generated by mkgenmidi.py from Freedoom's
 * GENMIDI bank.
 *
 * Copyright (c) 2001-2024 Contributors to the Freedoom project.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in the
 *     documentation and/or other materials provided with the distribution.
 *   * Neither the name of the Freedoom project nor the names of its
 *     contributors may be used to endorse or promote products derived from
 *     this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
 * IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
 * OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* 175 instruments of 36 bytes: 128 melodic (GM programs), 47 percussion
 * (GM notes 35-81): flags (2), fine tune (1), fixed note (1), 2 voices of
 * 16 bytes: modulator characteristic, attack/decay, sustain/release,
 * waveform, key scale, level; feedback/connection; carrier characteristic,
 * attack/decay, sustain/release, waveform, key scale, level; unused;
 * base note offset (2, signed). */

const unsigned char genmidi[175][36] = {''')
names = d[8 + 175 * 36:]
for i in range(175):
    b = d[8 + i * 36: 8 + (i + 1) * 36]
    name = names[i * 32:(i + 1) * 32].split(b'\0')[0].decode('latin-1').replace('*/', '')
    print('\t{' + ','.join('%d' % x for x in b) + '}, /* %d %s */' % (i, name))
print('};')

# OPL frequency numbers for octave 4 (block 4), 32 steps per semitone
import math
print('''
/* F-numbers of the notes C4..B4 at block 4 (OPL clock 49716 Hz), 32 steps
 * per semitone (pitch bend); octave n: block n */
const unsigned short fnum_tab[12 * 32] = {''')
v = []
for i in range(12 * 32):
    f = 440.0 * 2 ** ((60 + i / 32.0 - 69) / 12.0)
    v.append(round(f * 2 ** (20 - 4) / 49716.0))
for i in range(0, len(v), 16):
    print('\t' + ','.join('%d' % x for x in v[i:i + 16]) + ',')
print('};')
print('''
/* attenuation in OPL level steps (0.75 dB) for a MIDI value 0-127 (velocity,
 * volume, expression): 40 log10(v / 127) */
const unsigned char atten_tab[128] = {''')
a = [63] + [min(63, round(-40 * math.log10(x / 127.0) / 0.75)) for x in range(1, 128)]
for i in range(0, 128, 16):
    print('\t' + ','.join('%d' % x for x in a[i:i + 16]) + ',')
print('};')
